version: '3'
services:
  foodopia-app:
    image: coderhub1/foodopia:V3
    ports:
      - 80:80
    depends_on:
      - foodopia-db
    environment:
      - GOOGLE_CLOUD_PROJECT_ID=${GOOGLE_CLOUD_PROJECT_ID}
      - GOOGLE_CLOUD_API_KEY=${GOOGLE_CLOUD_API_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - DB_USER_PASSWORD=${SQL_USER_PASSWORD}
    networks:
      - app-network

  foodopia-db-service:
    image: coderhub1/foodopia_db:V3
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${SQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=foodogram
      - MYSQL_USER=vinayak
      - MYSQL_PASSWORD=${SQL_USER_PASSWORD}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
