apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-deployer-role
  namespace: foodopia
rules:
  - apiGroups: ["", "apps", "batch"]
    resources: ["pods", "deployments", "secrets", "configmaps", "services", "jobs" ]
    verbs: ["get", 'list', "watch", "delete", "create", "update", "patch"]