apiVersion:  rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-deployer-binding
  namespace: foodopia
subjects:
  - kind: ServiceAccount
    name: jenkins-deployer
    namespace: foodopia
roleRef:
  kind: Role
  name: jenkins-deployer-role
  apiGroup: rbac.authorization.k8s.io