apiVersion: v1
kind: Secret
metadata:
  name: jenkins-deployer-token
  namespace: foodopia
  annotations: 
    kubernetes.io/service-account.name: jenkins-deployer
type: kubernetes.io/service-account-token