apiVersion: v1
kind: ConfigMap
metadata: 
  name: non-sens-data
data: 
  GOOGLE_CLOUD_PROJECT_ID: 'foodogram-translate'
  S3_BUCKET_NAME: 'foodogram-recipes'
  AWS_REGION: 'eu-north-1'
  MYSQL_DATABASE: 'foodogram'
  MYSQL_USER: 'vinayak'