apiVersion: v1 
kind: Service
metadata:
  name: foodopia-db-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: foodopia-db
spec:
  type: ClusterIP
  selector:
    app: foodopia-db
  ports:
    - port: 3306
      targetPort: foodopia-db-port
      protocol: TCP
