apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: foodopia-ingress
  namespace: foodopia
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false" # SSL termination is handled by LoadBalancer
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true" # Redirect www to non-www
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  rules:
  - host: foodopia.life
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: elb-svc
            port:
              number: 80
  - host: www.foodopia.life
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: elb-svc
            port:
              number: 80
