apiVersion: v1
kind: Service
metadata:
  name: elb-svc
  namespace: foodopia
  labels:
    app: elb-svc
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:eu-north-1:982081083638:certificate/c7589630-7f75-4c02-a4b6-e5cbe4f73b09"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
spec:
  type: LoadBalancer
  selector:
    app: foodopia-app
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 80
      protocol: TCP