apiVersion: v1
kind: Service
metadata:
  name: elb-svc
  namespace: foodopia
  labels:
    app: elb-svc
spec:
  type: LoadBalancer
  selector:
    app: foodopia-app
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP