apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: foodopia-ingress
  namespace: foodopia
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip  # Routes traffic directly to pods' IPs
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'  # Enable both HTTP and HTTPS
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-north-1:381492127977:certificate/691ab551-e264-4325-83a8-da960fe67c5c  # ACM Certificate ARN for foodopia.life and www.foodopia.life
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-2016-08  # Optional: Specify a security policy
    # Redirect from www to non-www (foodopia.life)
    alb.ingress.kubernetes.io/actions.www-to-non-www-redirect: >
      {"type":"redirect","redirectConfig":{"protocol":"HTTPS","port":"443","host":"foodopia.life","statusCode":"HTTP_301"}}
    # Health check configuration for the ALB
    alb.ingress.kubernetes.io/healthcheck-path: /health  # Path for health checks
    alb.ingress.kubernetes.io/healthcheck-port: "80"  # Port for health checks (usually 80 or 443)
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "30"  # Health check interval
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "5"  # Timeout for health checks
    alb.ingress.kubernetes.io/healthy-threshold-count: "3"  # Number of consecutive successful health checks before marking a target as healthy
    alb.ingress.kubernetes.io/unhealthy-threshold-count: "3"  # Number of consecutive failed health checks before marking a target as unhealthy
spec:
  rules:
    # Rule for foodopia.life
    - host: foodopia.life
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: elb-svc
                port:
                  number: 80
    # Rule for www.foodopia.life with redirect to foodopia.life
    - host: www.foodopia.life
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: elb-svc
                port:
                  number: 80
